// AUTO-GENERATED - DO NOT EDIT
// Run: bun scripts/gen_builtin_skills.ts
// Source: src/node/builtinSkills/*.md and docs/

export const BUILTIN_SKILL_FILES: Record<string, Record<string, string>> = {
  init: {
    "SKILL.md": [
      "---",
      "name: init",
      "description: Bootstrap an AGENTS.md file in a new or existing project",
      "---",
      "",
      "<system>",
      "Use your tools to create or improve an AGENTS.md file in the root of the workspace which will serve as a contribution guide for AI agents.",
      "If an AGENTS.md file already exists, focus on additive improvement (preserve intent and useful information; refine, extend, and reorganize as needed) rather than replacing it wholesale.",
      "Inspect the workspace layout, code, documentation and git history to ensure correctness and accuracy.",
      "",
      "Ensure the following preamble exists at the top of the file before any other sections. Do not include the surrounding code fence backticks; only include the text.",
      "",
      "```md",
      "You are an experienced, pragmatic software engineering AI agent. Do not over-engineer a solution when a simple one is possible. Keep edits minimal. If you want an exception to ANY rule, you MUST stop and get permission first.",
      "```",
      "",
      "Recommended sections:",
      "",
      "- Project Overview (mandatory)",
      "  - Basic details about the project (e.g., high-level overview and goals).",
      "  - Technology choices (e.g., languages, databases, frameworks, libraries, build tools).",
      "- Reference (mandatory)",
      "  - List important code files.",
      "  - List important directories and basic code structure tips.",
      "  - Project architecture.",
      "- Essential commands (mandatory)",
      "  - build",
      "  - format",
      "  - lint",
      "  - test",
      "  - clean",
      "  - development server",
      "  - other _important_ scripts (use `find -type f -name '*.sh'` or similar)",
      "- Patterns (optional)",
      "  - List any important or uncommon patterns (compared to other similar codebases), with examples (e.g., how to authorize an HTTP request).",
      "  - List any important workflows and their steps (e.g., how to make a database migration).",
      "  - Testing patterns.",
      "- Anti-patterns (optional)",
      "  - Search git history and comments to find recurring mistakes or forbidden patterns.",
      "  - List each pattern and its reason.",
      "- Code style (optional)",
      "  - Style guide to follow (with link).",
      "- Commit and Pull Request Guidelines (mandatory)",
      "  - Required steps for validating changes before committing.",
      "  - Commit message conventions (read `git log`, or use `type: message` by default).",
      "  - Pull request description requirements.",
      "",
      "You can add other sections if they are necessary.",
      "If the information required for mandatory sections isn't available due to the workspace being empty or sparse, add TODO text in its place.",
      "Optional sections should be scrapped if the information is too thin.",
      "",
      "Some investigation tips:",
      "",
      "- Read existing lint configs, tsconfig, and CI workflows to find any style or layout rules.",
      '- Search for "TODO", "HACK", "FIXME", "don\'t", "never", "always" in comments.',
      "- Examine test files for patterns.",
      "- Read PR templates and issue templates if they exist.",
      "- Check for existing CONTRIBUTING.md, CODE_OF_CONDUCT.md, or similar documentation files.",
      "",
      "Some writing tips:",
      "",
      '- Each "do X" should have a corresponding "don\'t Y" where applicable.',
      "- Commands should be easily copy-pastable and tested.",
      "- Terms or phrases specific to this project should be explained on first use.",
      "- Anything that is against the norm should be explicitly highlighted and called out.",
      "",
      "Above all things:",
      "",
      "- The document must be clear and concise. Simple projects should need less than 400 words, but larger and more mature codebases will likely need 700+. Prioritize completeness over brevity.",
      "- Don't include useless fluff.",
      "- The document must be in Markdown format and use headings for structure.",
      "- Give examples where necessary or helpful (commands, directory paths, naming patterns).",
      "- Explanations and examples must be correct and specific to this codebase.",
      "- Maintain a professional, instructional tone.",
      "",
      "If the workspace is empty or sparse, ask the user for more information. Avoid hallucinating important decisions. You can provide suggestions to the user for language/technology/tool choices, but always respect the user's decision.",
      "",
      "- Project description and goals.",
      "- Language(s).",
      "- Technologies (database?), frameworks, libraries.",
      "- Tools.",
      "- Any other questions as you deem necessary.",
      "",
      "For empty or sparse workspaces ONLY, when finished writing/updating AGENTS.md, ask the user if they would like you to do the following:",
      "",
      "- initialize git IF it's not already set up (e.g., `git init`, `git remote add`, etc.)",
      "- write a concise README.md file",
      "- generate the bare minimum project scaffolding (e.g., initializing the package manager, writing a minimal build tool config)",
      "  </system>",
      "",
    ].join("\n"),
  },
  "unix-docs": {
    "SKILL.md": [
      "---",
      "name: unix-docs",
      "description: Index + offline snapshot of unix documentation (progressive disclosure).",
      "---",
      "",
      "# unix docs",
      "",
      "This built-in skill helps the agent answer questions about **unix** (Coding Agent Multiplexer) without dumping the entire docs into context.",
      "",
      "## How to use",
      "",
      "### Prefer: read the bundled docs snapshot (recommended)",
      "",
      "This skill bundles an **offline snapshot of the unix docs** under `references/docs/`.",
      "",
      "Why prefer the bundled snapshot?",
      "",
      "1. The docs tree below is guaranteed to match what’s embedded.",
      "2. It’s more likely to match *your installed unix version* (the live site may be ahead).",
      "",
      "To read a specific page:",
      "",
      "```ts",
      "agent_skill_read_file({",
      '  name: "unix-docs",',
      '  filePath: "references/docs/config/models.mdx",',
      "});",
      "```",
      "",
      "### Fallback: bundled docs",
      "",
      "If the bundled docs don't mention something, refer to the local documentation in the `docs/` directory.",
      "",
      "#### Docs tree (auto-generated)",
      "",
      "Use this index to find a page's:",
      "",
      "- **Docs route** (for `web_fetch`)",
      "- **Embedded file path** (for `agent_skill_read_file`)",
      "",
      "<!-- BEGIN DOCS_TREE -->",
      "- **Documentation**",
      "  - **Getting Started**",
      "    - Introduction (`/`) → `references/docs/index.mdx`",
      "    - Install (`/install`) → `references/docs/install.mdx` — Download and install Unix for macOS, Linux, and Windows",
      "    - **Models**",
      "      - Models (`/config/models`) → `references/docs/config/models.mdx` — Select and configure AI models in Unix",
      "      - Providers (`/config/providers`) → `references/docs/config/providers.mdx` — Configure API keys and settings for AI providers",
      "    - Why Parallelize? (`/getting-started/why-parallelize`) → `references/docs/getting-started/why-parallelize.mdx` — Use cases for running multiple AI agents in parallel",
      "    - Unix Codes (`/getting-started/unix-codes`) → `references/docs/getting-started/unix-codes.mdx` — Redeem free LLM token credits for evaluating Unix",
      "    - CLI (`/reference/cli`) → `references/docs/reference/cli.mdx` — Run one-off agent tasks from the command line with `unix run`",
      "  - **Workspaces**",
      "    - Workspaces (`/workspaces`) → `references/docs/workspaces/index.mdx` — Isolated development environments for parallel agent work",
      "    - Forking Workspaces (`/workspaces/fork`) → `references/docs/workspaces/fork.mdx` — Clone workspaces with conversation history to explore alternatives",
      "    - Message Sharing (`/workspaces/sharing`) → `references/docs/workspaces/sharing.mdx` — Share encrypted messages with cryptographic signatures via Unix",
      "    - **Compaction**",
      "      - Compaction (`/workspaces/compaction`) → `references/docs/workspaces/compaction/index.mdx` — Managing conversation context size with compaction",
      "      - Manual Compaction (`/workspaces/compaction/manual`) → `references/docs/workspaces/compaction/manual.mdx` — Commands for manually managing conversation context",
      "      - Automatic Compaction (`/workspaces/compaction/automatic`) → `references/docs/workspaces/compaction/automatic.mdx` — Let Unix automatically compact your conversations based on usage or idle time",
      "      - Customization (`/workspaces/compaction/customization`) → `references/docs/workspaces/compaction/customization.mdx` — Customize the compaction system prompt",
      "    - **Runtimes**",
      "      - Runtimes (`/runtime`) → `references/docs/runtime/index.mdx` — Configure where and how Unix executes agent workspaces",
      "      - Local Runtime (`/runtime/local`) → `references/docs/runtime/local.mdx` — Run agents directly in your project directory",
      "      - Worktree Runtime (`/runtime/worktree`) → `references/docs/runtime/worktree.mdx` — Isolated git worktree environments for parallel agent work",
      "      - SSH Runtime (`/runtime/ssh`) → `references/docs/runtime/ssh.mdx` — Run agents on remote hosts over SSH for security and performance",
      "      - Coder Runtime (`/runtime/coder`) → `references/docs/runtime/lattice.mdx` — Run agents on Lattice workspaces",
      "      - Docker Runtime (`/runtime/docker`) → `references/docs/runtime/docker.mdx` — Run agents in isolated Docker containers",
      "      - Dev Container Runtime (`/runtime/devcontainer`) → `references/docs/runtime/devcontainer.mdx` — Run agents in containers defined by devcontainer.json",
      "    - **Hooks**",
      "      - Init Hooks (`/hooks/init`) → `references/docs/hooks/init.mdx` — Run setup commands automatically when creating new workspaces",
      "      - Tool Hooks (`/hooks/tools`) → `references/docs/hooks/tools.mdx` — Block dangerous commands, lint after edits, and set up your environment",
      "      - Environment Variables (`/hooks/environment-variables`) → `references/docs/hooks/environment-variables.mdx` — Environment variables available in agent bash commands and hooks",
      "  - **Agents**",
      "    - Agents (`/agents`) → `references/docs/agents/index.mdx` — Define custom agents (modes + subagents) with Markdown files",
      "    - Instruction Files (`/agents/instruction-files`) → `references/docs/agents/instruction-files.mdx` — Configure agent behavior with AGENTS.md files",
      "    - Agent Skills (`/agents/agent-skills`) → `references/docs/agents/agent-skills.mdx` — Share reusable workflows and references with skills",
      "    - Plan Mode (`/agents/plan-mode`) → `references/docs/agents/plan-mode.mdx` — Review and collaborate on plans before execution",
      "    - System Prompt (`/agents/system-prompt`) → `references/docs/agents/system-prompt.mdx` — How Unix constructs the system prompt for AI models",
      "    - Prompting Tips (`/agents/prompting-tips`) → `references/docs/agents/prompting-tips.mdx` — Tips and tricks for getting the most out of your AI agents",
      "  - **Configuration**",
      "    - MCP Servers (`/config/mcp-servers`) → `references/docs/config/mcp-servers.mdx` — Extend agent capabilities with Model Context Protocol servers",
      "    - Project Secrets (`/config/project-secrets`) → `references/docs/config/project-secrets.mdx` — Manage environment variables and API keys for your projects",
      "    - Agentic Git Identity (`/config/agentic-git-identity`) → `references/docs/config/agentic-git-identity.mdx` — Configure a separate Git identity for AI-generated commits",
      "    - Keyboard Shortcuts (`/config/keybinds`) → `references/docs/config/keybinds.mdx` — Complete keyboard shortcut reference for Unix",
      "    - Notifications (`/config/notifications`) → `references/docs/config/notifications.mdx` — Configure how agents notify you about important events",
      "    - Vim Mode (`/config/vim-mode`) → `references/docs/config/vim-mode.mdx` — Vim-style editing in the Unix chat input",
      "  - **Guides**",
      "    - GitHub Actions (`/guides/github-actions`) → `references/docs/guides/github-actions.mdx` — Automate your workflows with unix run in GitHub Actions",
      "    - Agentic Git Identity (`/config/agentic-git-identity`) → `references/docs/config/agentic-git-identity.mdx` — Configure a separate Git identity for AI-generated commits",
      "    - Prompting Tips (`/agents/prompting-tips`) → `references/docs/agents/prompting-tips.mdx` — Tips and tricks for getting the most out of your AI agents",
      "  - **Integrations**",
      "    - VS Code Extension (`/integrations/vscode-extension`) → `references/docs/integrations/vscode-extension.mdx` — Pair Unix workspaces with VS Code and Cursor editors",
      "  - **Reference**",
      "    - Telemetry (`/reference/telemetry`) → `references/docs/reference/telemetry.mdx` — What Unix collects, what it doesn’t, and how to disable it",
      "    - Storybook (`/reference/storybook`) → `references/docs/reference/storybook.mdx` — Develop and test Unix UI states in isolation",
      "    - Terminal Benchmarking (`/reference/benchmarking`) → `references/docs/reference/benchmarking.mdx` — Run Terminal-Bench benchmarks with the Unix adapter",
      "    - AGENTS.md (`/AGENTS`) → `references/docs/AGENTS.md` — Agent instructions for AI assistants working on the Unix codebase",
      "<!-- END DOCS_TREE -->",
      "",
      "1. Read the docs navigation (source of truth for which pages exist):",
      "",
      "```ts",
      'agent_skill_read_file({ name: "unix-docs", filePath: "references/docs/docs.json" });',
      "```",
      "",
      "2. Read a specific page by path (mirrors `docs/` in the unix repo):",
      "",
      "- `/agents` → `references/docs/agents/index.mdx`",
      "- `/config/models` → `references/docs/config/models.mdx`",
      "- `/runtime` → `references/docs/runtime/index.mdx`",
      "",
      "```ts",
      "agent_skill_read_file({",
      '  name: "unix-docs",',
      '  filePath: "references/docs/config/models.mdx",',
      "});",
      "```",
      "",
      "Notes:",
      "",
      "- Many pages are `.mdx`; some are `.../index.mdx`.",
      "- Images are not embedded; you may see `/img/...` references.",
      "",
      "## When to use",
      "",
      "Use this skill when the user asks how unix works (workspaces, runtimes, agents, models, hooks, keybinds, etc.).",
      "",
      "## About",
      "",
      "DEV OS - parallel agentic workspace for internal use.",
      "",
    ].join("\n"),
  },
};
