#!/usr/bin/env bash
# Generate version.ts with git information
#
# In CI release builds (RELEASE_TAG set), use the tag directly to avoid false
# "-dirty" stamps from CI artifacts (node_modules, build outputs, etc.).
# Local builds continue using git describe --dirty for accurate dev info.

GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -n "$RELEASE_TAG" ]; then
  # CI release: use the authoritative tag, never dirty
  GIT_DESCRIBE="$RELEASE_TAG"
  echo "Release build: using RELEASE_TAG=${RELEASE_TAG}"
else
  # Local/dev build: use git describe with dirty detection
  GIT_DESCRIBE=$(git describe --tags --always --dirty 2>/dev/null || echo "unknown")

  # Debug output for dirty builds
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --verify HEAD >/dev/null 2>&1; then
    if ! git diff-index --quiet HEAD -- 2>/dev/null; then
      echo "⚠️  Git checkout is dirty; version will be stamped with '-dirty'."
      echo "Tracked dirty files:"
      git diff-index --name-only HEAD -- | sed 's/^/  - /'
    fi
  fi
fi

cat >src/version.ts <<EOF
// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "${GIT_COMMIT}",
  git_describe: "${GIT_DESCRIBE}",
  buildTime: "${TIMESTAMP}",
};
EOF

echo "Generated version.ts: ${GIT_DESCRIBE} (${GIT_COMMIT}) at ${TIMESTAMP}"
