// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "1d4e8ad4",
  git_describe: "1d4e8ad4-dirty",
  buildTime: "2026-01-28T17:35:51Z",
};
