// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "8acefd7e",
  git_describe: "8acefd7e-dirty",
  buildTime: "2026-01-28T21:01:33Z",
};
