// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "5b8807c1",
  git_describe: "5b8807c1-dirty",
  buildTime: "2026-01-31T13:38:18Z",
};
